export const COUNTRIES = [
  { value: "afg", label: "Afghanistan" },
  { value: "ala", label: "Aland Islands" },
  { value: "alb", label: "Albania" },
  { value: "dza", label: "Algeria" },
  { value: "asm", label: "American Samoa" },
  { value: "and", label: "Andorra" },
  { value: "ago", label: "Angola" },
  { value: "aia", label: "Anguilla" },
  { value: "ata", label: "Antarctica" },
  { value: "atg", label: "Antigua and Barbuda" },
  { value: "arg", label: "Argentina" },
  { value: "arm", label: "Armenia" },
  { value: "abw", label: "Aruba" },
  { value: "asi", label: "Asia (Unknown Country)" },
  { value: "aus", label: "Australia" },
  { value: "aut", label: "Austria" },
  { value: "aze", label: "Azerbaijan" },
  { value: "bhs", label: "Bahamas" },
  { value: "bhr", label: "Bahrain" },
  { value: "bgd", label: "Bangladesh" },
  { value: "brb", label: "Barbados" },
  { value: "blr", label: "Belarus" },
  { value: "bel", label: "Belgium" },
  { value: "blz", label: "Belize" },
  { value: "ben", label: "Benin" },
  { value: "bmu", label: "Bermuda" },
  { value: "btn", label: "Bhutan" },
  { value: "bol", label: "Bolivia" },
  { value: "bes", label: "Bonaire/Sint Eustatius/Saba" },
  { value: "bih", label: "Bosnia And Herzegovina" },
  { value: "bwa", label: "Botswana" },
  { value: "bvt", label: "Bouvet Island" },
  { value: "bra", label: "Brazil" },
  { value: "iot", label: "British Indian Ocean Territory" },
  { value: "vgb", label: "British Virgin Islands" },
  { value: "brn", label: "Brunei Darussalam" },
  { value: "bgr", label: "Bulgaria" },
  { value: "bfa", label: "Burkina Faso" },
  { value: "bdi", label: "Burundi" },
  { value: "khm", label: "Cambodia" },
  { value: "cmr", label: "Cameroon" },
  { value: "can", label: "Canada" },
  { value: "cpv", label: "Cape Verde" },
  { value: "cym", label: "Cayman Islands" },
  { value: "caf", label: "Central African Republic" },
  { value: "tcd", label: "Chad" },
  { value: "chl", label: "Chile" },
  { value: "chn", label: "China" },
  { value: "cxr", label: "Christmas Island" },
  { value: "cck", label: "Cocos (Keeling) Islands" },
  { value: "col", label: "Colombia" },
  { value: "com", label: "Comoros" },
  { value: "cog", label: "Congo" },
  { value: "cok", label: "Cook Islands" },
  { value: "cri", label: "Costa Rica" },
  { value: "civ", label: "Cote D Ivoire" },
  { value: "hrv", label: "Croatia" },
  { value: "cub", label: "Cuba" },
  { value: "cuw", label: "Curacao" },
  { value: "cyp", label: "Cyprus" },
  { value: "cze", label: "Czech Republic" },
  { value: "cod", label: "Democratic Republic Of The Congo" },
  { value: "dnk", label: "Denmark" },
  { value: "dji", label: "Djibouti" },
  { value: "dma", label: "Dominica" },
  { value: "dom", label: "Dominican Republic" },
  { value: "ecu", label: "Ecuador" },
  { value: "egy", label: "Egypt" },
  { value: "slv", label: "El Salvador" },
  { value: "gnq", label: "Equatorial Guinea" },
  { value: "eri", label: "Eritrea" },
  { value: "est", label: "Estonia" },
  { value: "eth", label: "Ethiopia" },
  { value: "eur", label: "Europe (Unknown Country)" },
  { value: "flk", label: "Falkland Islands (Malvinas)" },
  { value: "fro", label: "Faroe Islands" },
  { value: "fsm", label: "Federated States Of Micronesia" },
  { value: "fji", label: "Fiji" },
  { value: "fin", label: "Finland" },
  { value: "fra", label: "France" },
  { value: "guf", label: "French Guiana" },
  { value: "pyf", label: "French Polynesia" },
  { value: "atf", label: "French Southern Territories" },
  { value: "gab", label: "Gabon" },
  { value: "gmb", label: "Gambia" },
  { value: "geo", label: "Georgia" },
  { value: "deu", label: "Germany" },
  { value: "gha", label: "Ghana" },
  { value: "gib", label: "Gibraltar" },
  { value: "grc", label: "Greece" },
  { value: "grl", label: "Greenland" },
  { value: "grd", label: "Grenada" },
  { value: "glp", label: "Guadeloupe" },
  { value: "gum", label: "Guam" },
  { value: "gtm", label: "Guatemala" },
  { value: "ggy", label: "Guernsey" },
  { value: "gin", label: "Guinea" },
  { value: "gnb", label: "Guinea-Bissau" },
  { value: "guy", label: "Guyana" },
  { value: "hti", label: "Haiti" },
  { value: "hmd", label: "Heard And Mc Donald Islands" },
  { value: "vat", label: "Holy See (Vatican City State)" },
  { value: "hnd", label: "Honduras" },
  { value: "hkg", label: "Hong Kong" },
  { value: "hun", label: "Hungary" },
  { value: "isl", label: "Iceland" },
  { value: "ind", label: "India" },
  { value: "idn", label: "Indonesia" },
  { value: "irn", label: "Iran (Islamic Republic Of)" },
  { value: "irq", label: "Iraq" },
  { value: "irl", label: "Ireland" },
  { value: "imn", label: "Isle of Man" },
  { value: "isr", label: "Israel" },
  { value: "ita", label: "Italy" },
  { value: "jam", label: "Jamaica" },
  { value: "jpn", label: "Japan" },
  { value: "jey", label: "Jersey" },
  { value: "jor", label: "Jordan" },
  { value: "kaz", label: "Kazakhstan" },
  { value: "ken", label: "Kenya" },
  { value: "kir", label: "Kiribati" },
  { value: "kwt", label: "Kuwait" },
  { value: "kgz", label: "Kyrgyzstan" },
  { value: "lao", label: "Lao Peoples Democratic Republic" },
  { value: "lva", label: "Latvia" },
  { value: "lbn", label: "Lebanon" },
  { value: "lso", label: "Lesotho" },
  { value: "lbr", label: "Liberia" },
  { value: "lby", label: "Libyan Arab Jamahiriya" },
  { value: "lie", label: "Liechtenstein" },
  { value: "ltu", label: "Lithuania" },
  { value: "lux", label: "Luxembourg" },
  { value: "mac", label: "Macau" },
  { value: "mkd", label: "Macedonia" },
  { value: "mdg", label: "Madagascar" },
  { value: "mwi", label: "Malawi" },
  { value: "mys", label: "Malaysia" },
  { value: "mdv", label: "Maldives" },
  { value: "mli", label: "Mali" },
  { value: "mlt", label: "Malta" },
  { value: "mhl", label: "Marshall Islands" },
  { value: "mtq", label: "Martinique" },
  { value: "mrt", label: "Mauritania" },
  { value: "mus", label: "Mauritius" },
  { value: "myt", label: "Mayotte" },
  { value: "mex", label: "Mexico" },
  { value: "mda", label: "Moldova" },
  { value: "mco", label: "Monaco" },
  { value: "mng", label: "Mongolia" },
  { value: "mne", label: "Montenegro" },
  { value: "msr", label: "Montserrat" },
  { value: "mar", label: "Morocco" },
  { value: "moz", label: "Mozambique" },
  { value: "mmr", label: "Myanmar" },
  { value: "nam", label: "Namibia" },
  { value: "nru", label: "Nauru" },
  { value: "npl", label: "Nepal" },
  { value: "nld", label: "Netherlands" },
  { value: "ant", label: "Netherlands Antilles" },
  { value: "ncl", label: "New Caledonia" },
  { value: "nzl", label: "New Zealand" },
  { value: "nic", label: "Nicaragua" },
  { value: "ner", label: "Niger" },
  { value: "nga", label: "Nigeria" },
  { value: "niu", label: "Niue" },
  { value: "nfk", label: "Norfolk Island" },
  { value: "prk", label: "North Korea" },
  { value: "mnp", label: "Northern Mariana Islands" },
  { value: "nor", label: "Norway" },
  { value: "omn", label: "Oman" },
  { value: "pak", label: "Pakistan" },
  { value: "plw", label: "Palau" },
  { value: "pse", label: "Palestinian Territories" },
  { value: "pan", label: "Panama" },
  { value: "png", label: "Papua New Guinea" },
  { value: "pry", label: "Paraguay" },
  { value: "per", label: "Peru" },
  { value: "phl", label: "Philippines" },
  { value: "pcn", label: "Pitcairn" },
  { value: "pol", label: "Poland" },
  { value: "prt", label: "Portugal" },
  { value: "pri", label: "Puerto Rico" },
  { value: "qat", label: "Qatar" },
  { value: "***", label: "Reserved/Private" },
  { value: "reu", label: "Reunion" },
  { value: "rou", label: "Romania" },
  { value: "rus", label: "Russian Federation" },
  { value: "rwa", label: "Rwanda" },
  { value: "blm", label: "Saint Barthelemy" },
  { value: "kna", label: "Saint Kitts and Nevis" },
  { value: "lca", label: "Saint Lucia" },
  { value: "maf", label: "Saint Martin" },
  { value: "vct", label: "Saint Vincent and the Grenadines" },
  { value: "wsm", label: "Samoa" },
  { value: "smr", label: "San Marino" },
  { value: "stp", label: "Sao Tome and Principe" },
  { value: "sau", label: "Saudi Arabia" },
  { value: "sen", label: "Senegal" },
  { value: "srb", label: "Serbia" },
  { value: "syc", label: "Seychelles" },
  { value: "sle", label: "Sierra Leone" },
  { value: "sgp", label: "Singapore" },
  { value: "sxm", label: "Sint Maarten" },
  { value: "svk", label: "Slovakia (Slovak Republic)" },
  { value: "svn", label: "Slovenia" },
  { value: "slb", label: "Solomon Islands" },
  { value: "som", label: "Somalia" },
  { value: "zaf", label: "South Africa" },
  { value: "sgs", label: "South Georgia / South Sandwich Isl" },
  { value: "kor", label: "South Korea" },
  { value: "ssd", label: "South Sudan" },
  { value: "esp", label: "Spain" },
  { value: "lka", label: "Sri Lanka" },
  { value: "shn", label: "St. Helena" },
  { value: "spm", label: "St. Pierre And Miquelon" },
  { value: "sdn", label: "Sudan" },
  { value: "sur", label: "Suriname" },
  { value: "sjm", label: "Svalbard And Jan Mayen Islands" },
  { value: "swz", label: "Swaziland" },
  { value: "swe", label: "Sweden" },
  { value: "che", label: "Switzerland" },
  { value: "syr", label: "Syrian Arab Republic" },
  { value: "twn", label: "Taiwan Province Of China" },
  { value: "tjk", label: "Tajikistan" },
  { value: "tza", label: "Tanzania" },
  { value: "tha", label: "Thailand" },
  { value: "tls", label: "Timor-Leste" },
  { value: "tgo", label: "Togo" },
  { value: "tkl", label: "Tokelau" },
  { value: "ton", label: "Tonga" },
  { value: "tto", label: "Trinidad and Tobago" },
  { value: "tun", label: "Tunisia" },
  { value: "tur", label: "Turkey" },
  { value: "tkm", label: "Turkmenistan" },
  { value: "tca", label: "Turks and Caicos Islands" },
  { value: "tuv", label: "Tuvalu" },
  { value: "uga", label: "Uganda" },
  { value: "ukr", label: "Ukraine" },
  { value: "are", label: "United Arab Emirates" },
  { value: "gbr", label: "United Kingdom" },
  { value: "usa", label: "United States" },
  { value: "?", label: "Unknown" },
  { value: "ury", label: "Uruguay" },
  { value: "umi", label: "Us Minor Outlying Islands" },
  { value: "vir", label: "Us Virgin Islands" },
  { value: "uzb", label: "Uzbekistan" },
  { value: "vut", label: "Vanuatu" },
  { value: "ven", label: "Venezuela" },
  { value: "vnm", label: "Viet Nam" },
  { value: "wlf", label: "Wallis And Futuna Islands" },
  { value: "esh", label: "Western Sahara" },
  { value: "yem", label: "Yemen" },
  { value: "zmb", label: "Zambia" },
  { value: "zwe", label: "Zimbabwe" }
];

export const DMA = [
  { value: "1", label: "DMA Example 1" },
  { value: "2", label: "DMA Example 2" },
  { value: "3", label: "DMA Example 3" },
  { value: "4", label: "DMA Example 4" },
  { value: "5", label: "DMA Example 5" },
  { value: "6", label: "DMA Example 6" },
  { value: "7", label: "DMA Example 7" },
  { value: "8", label: "DMA Example 8" },
  { value: "9", label: "DMA Example 9" },
  { value: "10", label: "DMA Example 10" },
  { value: "11", label: "DMA Example 11" },
  { value: "12", label: "DMA Example 12" },
  { value: "13", label: "DMA Example 13" },
  { value: "14", label: "DMA Example 14" },
  { value: "15", label: "DMA Example 15" },
  { value: "16", label: "DMA Example 16" },
  { value: "17", label: "DMA Example 17" },
  { value: "18", label: "DMA Example 18" },
  { value: "19", label: "DMA Example 19" },
  { value: "20", label: "DMA Example 20" },
];
